"use client";

import { useMemo, useState } from "react";
import { withBase } from "@/lib/paths";

type Submission = { id: string; kind: "report" | "my_news"; status: string; payload: Record<string, unknown>; contact: string | null; createdAt: string; articleId: string | null };
const labels: Record<string, string> = { received: "Получен", in_review: "В проверка", verified: "Потвърден", rejected: "Отхвърлен", published: "Публикуван" };

export function SubmissionsManager({ initial }: { initial: Submission[] }) {
  const [items, setItems] = useState(initial);
  const [status, setStatus] = useState("all");
  const [kind, setKind] = useState("all");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<Submission | null>(null);
  const shown = useMemo(() => items.filter((item) => (status === "all" || item.status === status) && (kind === "all" || item.kind === kind) && JSON.stringify(item.payload).toLowerCase().includes(query.toLowerCase())), [items, status, kind, query]);
  async function change(item: Submission, next: string) {
    const response = await fetch(withBase("/api/editor/submissions/"), { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: item.id, status: next }) });
    if (!response.ok) return;
    setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, status: next } : entry));
    setSelected((current) => current?.id === item.id ? { ...current, status: next } : current);
  }
  return <div className="space-y-4">
    <div><h1 className="text-2xl font-extrabold tracking-tight text-ink sm:text-3xl">Сигнали от граждани</h1><p className="mt-1 text-sm text-muted">Преглед, проверка и редакционно управление на подадени сигнали и материали.</p></div>
    <div className="np-card flex flex-wrap gap-2 p-3"><input className="np-input max-w-xs py-2 text-sm" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Търсене в съдържанието" /><select className="np-input w-auto py-2 text-sm" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Всички статуси</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select className="np-input w-auto py-2 text-sm" value={kind} onChange={(event) => setKind(event.target.value)}><option value="all">Всички типове</option><option value="report">Сигнали</option><option value="my_news">Моята новина</option></select></div>
    <div className="np-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-surface-2 text-xs font-bold tracking-wide text-muted uppercase"><tr><th className="px-4 py-3">Получен</th><th className="px-4 py-3">Тип</th><th className="px-4 py-3">Съдържание</th><th className="px-4 py-3">Статус</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-line">{shown.map((item) => <tr key={item.id} className="hover:bg-surface-2/50"><td className="whitespace-nowrap px-4 py-3 text-muted">{new Date(item.createdAt).toLocaleString("bg-BG")}</td><td className="px-4 py-3 font-semibold text-ink">{item.kind === "report" ? "Сигнал" : "Моята новина"}</td><td className="max-w-md px-4 py-3 text-muted">{String(item.payload.description ?? item.payload.whatHappened ?? item.payload.workingTitle ?? "—")}</td><td className="px-4 py-3"><span className="rounded-full bg-accent/10 px-2 py-1 text-xs font-bold text-accent">{labels[item.status] ?? item.status}</span></td><td className="px-4 py-3 text-right"><button type="button" onClick={() => setSelected(item)} className="np-btn np-btn-secondary px-3 py-1.5 text-xs">Отвори</button></td></tr>)}</tbody></table></div>{!shown.length ? <p className="p-10 text-center text-sm text-muted">Няма сигнали по тези филтри.</p> : null}</div>
    {selected ? <dialog open className="fixed inset-0 z-50 m-auto max-h-[85dvh] w-[min(48rem,calc(100vw-2rem))] overflow-auto rounded-2xl border border-line bg-surface p-0 shadow-2xl"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="font-extrabold text-ink">{selected.kind === "report" ? "Сигнал" : "Моята новина"}</h2><p className="text-xs text-muted">{new Date(selected.createdAt).toLocaleString("bg-BG")}</p></div><button type="button" onClick={() => setSelected(null)} className="text-xl text-muted">×</button></div><div className="space-y-4 p-5">{selected.kind === "my_news" ? <div className="grid gap-3 sm:grid-cols-2"><div><p className="text-[11px] font-bold uppercase text-muted">Работно заглавие</p><p className="font-bold text-ink">{String(selected.payload.workingTitle ?? "—")}</p></div><div><p className="text-[11px] font-bold uppercase text-muted">Име за публикуване</p><p className="text-body">{String(selected.payload.publishName ?? "—")}</p></div><div className="sm:col-span-2"><p className="text-[11px] font-bold uppercase text-muted">Къде и кога</p><p className="whitespace-pre-wrap text-body">{String(selected.payload.whereWhen ?? "—")}</p></div></div> : null}<div><p className="text-[11px] font-bold uppercase text-muted">Описание</p><p className="whitespace-pre-wrap text-sm leading-relaxed text-body">{String(selected.payload.description ?? selected.payload.whatHappened ?? "—")}</p></div><p className="text-sm text-muted">Контакт: {selected.contact || "Не е посочен"}</p>{Array.isArray(selected.payload.files) && selected.payload.files.length ? <div><p className="mb-2 text-xs font-bold uppercase text-muted">Прикачени снимки</p><div className="grid grid-cols-2 gap-3">{(selected.payload.files as { path: string }[]).map((photo) => <img key={photo.path} src={withBase(`/api/editor/submissions/photo/?path=${encodeURIComponent(photo.path)}`)} alt="Снимка към сигнала" className="aspect-[4/3] w-full rounded-xl object-cover" />)}</div></div> : null}{selected.payload.position && typeof selected.payload.position === "object" ? <p className="text-sm text-muted">Локация: {JSON.stringify(selected.payload.position)} </p> : null}<div className="flex flex-wrap gap-2">{Object.entries(labels).map(([value, label]) => <button key={value} type="button" onClick={() => void change(selected, value)} className={`rounded-lg px-3 py-2 text-xs font-bold ${selected.status === value ? "bg-accent text-white" : "bg-surface-2 text-ink"}`}>{label}</button>)}</div>{selected.articleId ? <a href={withBase(`/articles/${selected.articleId}`)} className="text-sm font-bold text-link">Отвори свързаната статия →</a> : null}</div></dialog> : null}
  </div>;
}
