import type { CameraEntry } from "../types";

/** Hand-checked public camera catalog (LP-05). embedUrl = public iframe (rtsp.me / YouTube / meter player). */
export const CAMERA_CATALOG: readonly CameraEntry[] = [
  {
    slug: "plovdiv-komatevo",
    name: "Коматево — Център",
    place: "кв. Кomatевo, Пловдив",
    direction: null,
    category: "city",
    owner: "YouTube",
    sourceUrl: "https://www.youtube.com/watch?v=qVdC1q49TdU",
    access: "iframe",
    embedUrl: "https://www.youtube.com/embed/qVdC1q49TdU",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: "За Читалище вижте „Коматево — Читалище“.",
  },
  {
    slug: "plovdiv-komatevo-chitalishte",
    name: "Коматево — Читалище",
    place: "кв. Коматево, Пловдив",
    direction: null,
    category: "city",
    owner: "YouTube",
    sourceUrl: "https://www.youtube.com/watch?v=8p-QOW9jSjw",
    access: "iframe",
    embedUrl: "https://www.youtube.com/embed/8p-QOW9jSjw",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: null,
  },
  {
    slug: "plovdiv-alyosha",
    name: "Панорама — Младежки хълм и Альоша",
    place: "Пловдив",
    direction: "към тепетата",
    category: "city",
    owner: "meter.ac",
    sourceUrl: "https://meter.ac/gs/nodes/N233/photo.html",
    access: "iframe",
    embedUrl: "https://meter.ac/gs/nodes/N233/photo.html",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: "Метео камера.",
  },
  {
    slug: "plovdiv-vasil-aprilov",
    name: "ул. „Васил Априлов“ 126",
    place: "Пловдив",
    direction: "към центъра",
    category: "traffic",
    owner: "In-Com",
    sourceUrl: "https://rtsp.me/embed/fVKge6CvGgZS4av2/",
    access: "iframe",
    embedUrl: "https://rtsp.me/embed/fVKge6CvGgZS4av2/",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: null,
  },
  {
    slug: "plovdiv-bunardzhik-roundabout",
    name: "Център — кръгово бул. „6-ти септември“",
    place: "Пловдив",
    direction: "към Бунарджика и Родопите",
    category: "traffic",
    owner: "In-Com",
    sourceUrl: "https://rtsp.me/embed/omoTw7kqjiUpdBES/",
    access: "iframe",
    embedUrl: "https://rtsp.me/embed/omoTw7kqjiUpdBES/",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: null,
  },
  {
    slug: "plovdiv-6-septemvri",
    name: "бул. „6-ти септември“",
    place: "Пловдив (Кършияка)",
    direction: null,
    category: "traffic",
    owner: "In-Com",
    sourceUrl: "https://rtsp.me/embed/W0NmNFwdWZ9bgDSD/",
    access: "iframe",
    embedUrl: "https://rtsp.me/embed/W0NmNFwdWZ9bgDSD/",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: null,
  },
  {
    slug: "plovdiv-centar-rodopi",
    name: "Панорама към Родопите",
    place: "промишлена зона, Пловдив",
    direction: "към Родопите",
    category: "city",
    owner: "meter.ac",
    sourceUrl: "https://meter.ac/gs/nodes/N06/photo.html",
    access: "iframe",
    embedUrl: "https://meter.ac/gs/nodes/N06/photo.html",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: "Метеорологична станция.",
  },
  {
    slug: "plovdiv-palm-airport",
    name: "Палм Център — близо летище Пловдив",
    place: "Палм Център, ~2 km от летището",
    direction: null,
    category: "region",
    owner: "stringmeteo.com",
    sourceUrl: "https://www.stringmeteo.com/stations/palmcenter/webcamimage.jpg",
    access: "iframe",
    embedUrl: "https://www.stringmeteo.com/stations/palmcenter/webcamimage.jpg",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: null,
  },
  {
    slug: "plovdiv-kuklen",
    name: "Куклен",
    place: "гр. Куклен, 308 m н.в.",
    direction: "към Родопите",
    category: "region",
    owner: "meter.ac",
    sourceUrl: "https://meter.ac/gs/nodes/N219/photo.html",
    access: "iframe",
    embedUrl: "https://meter.ac/gs/nodes/N219/photo.html",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: "Метео станция.",
  },
  {
    slug: "plovdiv-trakia",
    name: "кв. „Тракия“",
    place: "Пловдив",
    direction: null,
    category: "city",
    owner: "In-Com",
    sourceUrl: "https://rtsp.me/embed/7qEcnXr3oNn091t9/",
    access: "iframe",
    embedUrl: "https://rtsp.me/embed/7qEcnXr3oNn091t9/",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: null,
  },
  {
    slug: "plovdiv-trakia-rooftop",
    name: "жк „Тракия“ — покрив (изглед 1)",
    place: "жк „Тракия“, Пловдив",
    direction: null,
    category: "city",
    owner: "In-Com",
    sourceUrl: "https://rtsp.me/embed/Bvx1k3z5dYFFICod/",
    access: "iframe",
    embedUrl: "https://rtsp.me/embed/Bvx1k3z5dYFFICod/",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: "Втори изглед — „Тракия — покрив (изглед 2)“.",
  },
  {
    slug: "plovdiv-trakia-rooftop-2",
    name: "жк „Тракия“ — покрив (изглед 2)",
    place: "жк „Тракия“, Пловдив",
    direction: null,
    category: "city",
    owner: "In-Com",
    sourceUrl: "https://rtsp.me/embed/mEVFOlWiousnlOUh/",
    access: "iframe",
    embedUrl: "https://rtsp.me/embed/mEVFOlWiousnlOUh/",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: null,
  },
  {
    slug: "asenovgrad-panorama",
    name: "Асеновград — панорама",
    place: "Асеновград",
    direction: "към Родопите",
    category: "region",
    owner: "In-Com",
    sourceUrl: "https://rtsp.me/embed/FD4SZSlDHpF8fEkU/",
    access: "iframe",
    embedUrl: "https://rtsp.me/embed/FD4SZSlDHpF8fEkU/",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: null,
  },
  {
    slug: "asenovgrad-ii-86",
    name: "Асеновград — път II-86",
    place: "Асеновград",
    direction: "Пловдив — Смолян",
    category: "traffic",
    owner: "In-Com",
    sourceUrl: "https://rtsp.me/embed/FD4SZSlDHpF8fEkU/",
    access: "iframe",
    embedUrl: "https://rtsp.me/embed/FD4SZSlDHpF8fEkU/",
    streamStatus: "verified",
    lastChecked: "2026-09-25",
    notes: "Същият публичен поток като панорамата.",
  },
  {
    slug: "sba-omv-plovdiv",
    name: "OMV Пловдив",
    place: "бул. „Мария Луиза“, Пловдив",
    direction: null,
    category: "traffic",
    owner: "СБА",
    sourceUrl: "https://www.sba.bg/cctv",
    access: "link",
    embedUrl: null,
    streamStatus: "unverified",
    lastChecked: "2026-09-25",
    notes: "Публична страница на СБА.",
  },
  {
    slug: "sba-omv-orizovo",
    name: "OMV Оризово",
    place: "Оризово, АМ Тракия",
    direction: null,
    category: "traffic",
    owner: "СБА",
    sourceUrl: "https://www.sba.bg/cctv",
    access: "link",
    embedUrl: null,
    streamStatus: "unverified",
    lastChecked: "2026-09-25",
    notes: "Публична страница на СБА.",
  },
] as const;

export function getCamera(slug: string): CameraEntry | undefined {
  return CAMERA_CATALOG.find((camera) => camera.slug === slug);
}

export function hasVerifiedLiveCamera(): boolean {
  return CAMERA_CATALOG.some((camera) => camera.streamStatus === "verified");
}

export function canPlayInApp(camera: CameraEntry): boolean {
  return camera.access === "iframe" && Boolean(camera.embedUrl) && camera.streamStatus === "verified";
}
