// Generated by scripts/build-studio-photo.mjs — do not edit by hand.
// Source: 1915x821, content hash 83bcc6bf.
export const STUDIO_PHOTO = {
  hash: "83bcc6bf",
  width: 1915,
  height: 821,
  sizes: "100vw",
  avif: "/brand/podcast-studio-1915-83bcc6bf.avif",
  fallback: "/brand/podcast-studio-1915-83bcc6bf.jpg",
  srcsetAvif: "/brand/podcast-studio-800-83bcc6bf.avif 800w, /brand/podcast-studio-1280-83bcc6bf.avif 1280w, /brand/podcast-studio-1600-83bcc6bf.avif 1600w, /brand/podcast-studio-1915-83bcc6bf.avif 1915w",
  srcsetWebp: "/brand/podcast-studio-800-83bcc6bf.webp 800w, /brand/podcast-studio-1280-83bcc6bf.webp 1280w, /brand/podcast-studio-1600-83bcc6bf.webp 1600w, /brand/podcast-studio-1915-83bcc6bf.webp 1915w",
  srcsetJpeg: "/brand/podcast-studio-800-83bcc6bf.jpg 800w, /brand/podcast-studio-1280-83bcc6bf.jpg 1280w, /brand/podcast-studio-1600-83bcc6bf.jpg 1600w, /brand/podcast-studio-1915-83bcc6bf.jpg 1915w",
  lqip: "data:image/avif;base64,AAAAHGZ0eXBhdmlmAAAAAG1pZjFhdmlmbWlhZgAAANZtZXRhAAAAAAAAACFoZGxyAAAAAAAAAABwaWN0AAAAAAAAAAAAAAAAAAAAACJpbG9jAAAAAERAAAEAAQAAAAAA+gABAAAAAAAAAJcAAAAjaWluZgAAAAAAAQAAABVpbmZlAgAAAAABAABhdjAxAAAAAA5waXRtAAAAAAABAAAAVmlwcnAAAAA4aXBjbwAAAAxhdjFDgSACAAAAABRpc3BlAAAAAAAAACAAAAAOAAAAEHBpeGkAAAAAAwgICAAAABZpcG1hAAAAAAAAAAEAAQOBAgMAAACfbWRhdBIACgg4EP+toCGg0jKIARrCYuTgCQAhQYABAPELtBiI62yR/haMHXmVqdSPeQD0OcgUk0vyAhBh3X2+1wQ9QNvRw6gD/4HoYWgmIbOHXF8MInPZhltwh0nnUqa8qz0q2NwL6THqJ2PXRHt/uKAAgmBt4cFyNref6ilTIIl9qHqoWWHhb5X3PWzwYr9+N1nEaEx67gV19lg=",
} as const;
